export const CHANGE_USER_DETAILS = "CHANGE_USER_DETAILS";
export const SUBMIT_USER_DETAILS = "SUBMIT_USER_DETAILS";
export const DISPLAY_USER_ERROR = "DISPLAY_USER_ERROR";
export const CHANGE_PRIVACY_DETAILS = "CHANGE_PRIVACY_DETAILS";
export const SUBMIT_PRIVACY_DETAILS = "SUBMIT_PRIVACY_DETAILS";
